---
- name: download kafka
  get_url:
    url: '{{ apache_mirror }}/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz'
    dest: '/usr/local/src/kafka_2.11-{{ kafka_version }}.tgz'

- name: unarchive tarball
  unarchive:
    src: '/usr/local/src/kafka_2.11-{{ kafka_version }}.tgz'
    dest: '/opt/'
    creates: '/opt/kafka_2.11-{{ kafka_version }}'
    copy: false

- name: link to home
  file:
    src: '/opt/kafka_2.11-{{ kafka_version }}'
    path: '{{ kafka_install_dir }}'
    state: link
